---
version: '2'
services:
  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./njinx.conf:/etc/nginx/conf.d/default.confbd
    volumes from:
      - php
  php:
    build: php-7.0-fpm-custom
    environment:
      - TYPO3_CONTEXT=Development/Docker
    links:
      - db
      - redis
    volunes:
      - ./htdocs:var/www/html
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volunes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:latest